# Numerical Analysis With Python - Part 0

## Aljabar Linear - Vektor dan Matrix

### Vektor

Vektor baris
$$\displaystyle \overrightarrow{V_1} = \left[
\begin{array}{ccc}
1 & -5 & 3 & 2 & 4
\end{array}
\right]$$

Vektor Kolom
$$\displaystyle \overrightarrow{V_2} = \left[
\begin{array}{ccc}
1 \\
2 \\
3 \\
4 \\
5
\end{array}
\right]$$



In [ ]:
import numpy as np
vector_row = np.array([
        [1, -5, 3, 2, 4]
        ])
vector_column = np.array([
        [1],
        [2],
        [3],
        [4],
        [5]
        ])
print(vector_row.shape)
print(vector_column.shape)


: 

**Norma vektor** adalah besaran yang mengukur panjang suatu vektor. Norma vektor dapat didefinisikan dengan beberapa cara, tergantung pada metrik yang digunakan (rumus jarak yang dipilih). Yang paling umum adalah norma L2, yang dihitung menggunakan rumus jarak yang mungkin Anda kenal dari sekolah dasar. Norma L2 dari suatu vektor $v$ dilambangkan dengan $\Vert v \Vert_{2}$ dan $\Vert v \Vert_{2} = \sqrt{\sum_i v_i^2}$. Ini kadang-kadang juga disebut panjang Euclidean dan mengacu pada panjang "fisik" suatu vektor dalam ruang satu, dua, atau tiga dimensi.

**Norma L1**, atau "Manhattan Distance", dihitung sebagai $\Vert v \Vert_{1} = \sum_i |v_i|$, dan dinamai sesuai dengan struktur jalan seperti grid di New York City. Secara umum, norma p, $L_p$, suatu vektor adalah $\Vert v \Vert_{p} = \sqrt[p]{(\sum_i v_i^p)}$. Norma $L_\infty$ adalah norma p, di mana $p = \infty$. Norma $L_\infty$ ditulis sebagai $||v||_\infty$ dan sama dengan nilai absolut maksimum dalam $v$.

Norma vektor dapat digunakan untuk berbagai tujuan, seperti:

* Mengukur panjang vektor
* Menormalisasi vektor
* Menghitung jarak antara dua vektor
* Menilai kesalahan numerik

Berikut adalah beberapa contoh penggunaan norma vektor:

* **Mengukur panjang vektor:** Norma L2 dapat digunakan untuk mengukur panjang vektor. Misalnya, jika vektor $v = [1, 2, 3]$, maka norma L2 dari vektor tersebut adalah $\Vert v \Vert_{2} = \sqrt{1^2 + 2^2 + 3^2} = 3.74$. Ini berarti bahwa panjang vektor v adalah 3.74.
* **Menormalisasi vektor:** Norma L2 dapat digunakan untuk menormalisasi vektor. Normalisasi vektor adalah proses mengubah vektor sehingga panjangnya menjadi 1. Misalnya, jika vektor $v = [1, 2, 3]$, maka norma L2 dari vektor tersebut adalah $\Vert v \Vert_{2} = 3.74$. Untuk menormalisasi vektor tersebut, kita dapat membagi setiap elemen vektor dengan norma L2-nya. Hasilnya adalah vektor $v_norm = [1/3.74, 2/3.74, 3/3.74]$, yang memiliki panjang 1.
* **Menghitung jarak antara dua vektor:** Norma L2 dapat digunakan untuk menghitung jarak antara dua vektor. Jarak antara dua vektor adalah panjang vektor yang menghubungkan dua vektor tersebut. Misalnya, jika vektor $v1 = [1, 2, 3]$ dan vektor $v2 = [4, 5, 6]$, maka jarak antara dua vektor tersebut adalah $||v1 - v2||_{2} = \sqrt{3^2 + 3^2 + 3^2} = 3.74$.
* **Menilai kesalahan numerik:** Norma L2 dapat digunakan untuk menilai kesalahan numerik. Kesalahan numerik adalah perbedaan antara hasil perhitungan numerik dan hasil perhitungan analitik. Misalnya, jika kita menghitung nilai dari fungsi $f(x) = x^2$ pada titik $x = 1$ dengan menggunakan perhitungan numerik, maka hasil perhitungan tersebut mungkin berbeda dari hasil perhitungan analitik. Kita dapat menggunakan norma L2 untuk menilai seberapa besar kesalahan numerik tersebut.

Norma vektor adalah konsep yang penting dalam matematika dan fisika, dan memiliki banyak aplikasi dalam berbagai bidang, seperti ilmu komputer, teknik, dan keuangan.

In [83]:
from numpy.linalg import norm
new_vector = vector_row.T
print(new_vector)
norm_1 = norm(new_vector, 1)
norm_2 = norm(new_vector, 2)
norm_inf = norm(new_vector, np.inf)
print("L_1 is: ",norm_1)
print("L_2 is: ",round(norm_2,1))
print("L_inf is: ",norm_inf)

[[ 1]
 [-5]
 [ 3]
 [ 2]
 [ 4]]
L_1 is:  15.0
L_2 is:  7.4
L_inf is:  5.0


### Operasi Vektor
Penambahan vektor dan perkalian skalar dengan vektor adalah operasi dasar dalam matematika vektor. Penambahan vektor dapat digunakan untuk menggabungkan dua vektor menjadi satu vektor baru, sedangkan perkalian skalar dengan vektor dapat digunakan untuk mengubah panjang dan arah vektor.

**Penambahan vektor**

Penambahan vektor adalah operasi yang menggabungkan dua vektor menjadi satu vektor baru. Vektor baru tersebut memiliki komponen yang merupakan jumlah dari komponen masing-masing vektor yang ditambahkan.

Misalnya, jika kita memiliki dua vektor $v = (1, 2, 3)$ dan $w = (4, 5, 6)$, maka penambahan vektor dari $v$ dan $w$ adalah vektor $u = v + w = (1 + 4, 2 + 5, 3 + 6) = (5, 7, 9)$.

**Perkalian skalar dengan vektor**

Perkalian skalar dengan vektor adalah operasi yang mengubah panjang dan arah vektor. Vektor baru tersebut memiliki komponen yang merupakan perkalian dari masing-masing komponen vektor dengan skalar.

Misalnya, jika kita memiliki vektor $v = (1, 2, 3)$ dan skalar $\alpha = 2$, maka perkalian skalar dari $\alpha$ dan $v$ adalah vektor $x = \alpha v = 2(1, 2, 3) = (2, 4, 6)$.

**Dot Product**

Hasil kali dot dari dua vektor adalah operasi yang mengukur kesamaan arah dari dua vektor tersebut. Hasil kali dot dari dua vektor dilambangkan dengan $\cdot$.

Misalnya, jika kita memiliki dua vektor $v = (1, 2, 3)$ dan $w = (4, 5, 6)$, maka hasil kali dot dari $v$ dan $w$ adalah $v \cdot w = 1 \cdot 4 + 2 \cdot 5 + 3 \cdot 6 = 32$.

Hasil kali dot dari dua vektor dapat digunakan untuk menghitung sudut antara dua vektor. Sudut antara dua vektor $\theta$ didefinisikan oleh rumus:

$$
v \cdot w = \Vert v \Vert_{2} \Vert w \Vert_{2} \cos{\theta}
$$

Dimana $\Vert v \Vert_{2}$ dan $\Vert w \Vert_{2}$ adalah panjang dari vektor $v$ dan $w$ masing-masing.

Jika hasil kali dot dari dua vektor adalah 0, maka kedua vektor tersebut dikatakan tegak lurus atau ortogonal.

Berikut adalah beberapa contoh penggunaan penambahan vektor, perkalian skalar dengan vektor, dan hasil kali dot:

* **Penambahan vektor dapat digunakan untuk menghitung perpindahan total dari suatu objek.** Misalnya, jika objek bergerak sejauh $v$ meter ke timur dan kemudian $w$ meter ke utara, maka perpindahan total objek tersebut adalah $v + w$.
* **Perkalian skalar dengan vektor dapat digunakan untuk mengubah kecepatan dan percepatan dari suatu objek.** Misalnya, jika objek bergerak dengan kecepatan $v$ meter per detik dan kemudian kecepatannya dilipatgandakan oleh $\alpha$, maka kecepatan baru objek tersebut adalah $\alpha v$.
* **Hasil kali dot dapat digunakan untuk menghitung proyeksi dari suatu vektor ke vektor lainnya.** Misalnya, jika kita memiliki dua vektor $v$ dan $w$, maka proyeksi dari vektor $v$ ke vektor $w$ adalah $\frac{v \cdot w}{\Vert w \Vert_{2}}w$.

**Contoh 1 : Perkalian Dot Vektor**
$$\displaystyle \overrightarrow{V_1} \cdot \overrightarrow{V_2} = \left[
\begin{array}{ccc}
1 & -5 & 3 & 2 & 4
\end{array}
\right] \cdot \left[
\begin{array}{ccc}
1 \\
2 \\
3 \\
4 \\
5
\end{array}
\right] \\
\\
= \left(1\cdot 1 \right) + \left(\left(-5\right) \cdot 2 \right) + \left( 3\cdot 3\right) + 2 \cdot 4 + 4 \cdot 5 \\
= 1 - 10 + 9 + 8 + 20 = 28
$$


In [84]:
dot = np.dot(vector_row, vector_column )
print("Hasil perkalian dot :",dot)
print(dot.shape)

Hasil perkalian dot : [[28]]
(1, 1)


**Contoh 2 : Carilah Sudut antara $v = [10, 9, 3]$ and $w = [2, 5, 12]$.**

In [ ]:
from numpy import arccos, dot

v = np.array([[10, 9, 3]])
w = np.array([[2, 5, 12]])
theta = \
    arccos(dot(v, w.T)/(norm(v)*norm(w)))
print(theta)

: 

**Penjelasan**

Hasil kali silang dari dua vektor, $v$ dan $w$, ditulis $v \times w$. Hasil kali silang didefinisikan oleh $v \times w = \Vert v \Vert_{2}\Vert w \Vert_{2}\sin{(\theta)} \textit{n}$, di mana $\theta$ adalah sudut antara $v$ dan $w$ (yang dapat dihitung dari hasil kali dot) dan **$n$** adalah vektor yang tegak lurus terhadap $v$ dan $w$ dengan panjang 1 (yaitu, panjangnya adalah satu). Interpretasi geometris dari hasil kali silang adalah vektor yang tegak lurus terhadap $v$ dan $w$ dengan panjang sama dengan luas yang diapit oleh jajaran genjang yang dibuat oleh kedua vektor tersebut.

Misalnya, jika kita memiliki dua vektor $v = (1, 2, 3)$ dan $w = (4, 5, 6)$, maka hasil kali silang dari $v$ dan $w$ adalah $v \times w = (-3, 6, -3)$.

---

### Matrix

Berikut adalah penjelasan yang lebih padat tentang materi yang Anda berikan:

**Kemandirian linear**

Seperangkat vektor dikatakan linier independen jika tidak ada vektor dalam himpunan tersebut yang dapat ditulis sebagai kombinasi linear dari vektor-vektor lainnya.

Contoh: Vektor $v = [1, 1, 0]$, $w = [1, 0, 0]$, dan $u = [0, 0, 1]$ adalah linier independen karena tidak ada vektor dalam himpunan tersebut yang dapat ditulis sebagai kombinasi linear dari vektor-vektor lainnya.

**Matriks**

Matriks adalah tabel persegi panjang angka yang terdiri dari $m$ baris dan $n$ kolom. Normal matriks dapat dianggap sebagai jenis khusus dari norma vektor, jika kita memperlakukan elemen $m \times n$ dari $M$ sebagai elemen dari vektor $mn$ dimensi, maka norma-p dari vektor ini dapat ditulis sebagai:

$$\Vert M \Vert_{p} = \sqrt[p]{(\sum_i^m \sum_j^n |a_{ij}|^p)}$$

Anda dapat menghitung norma matriks menggunakan fungsi `norm` yang sama di `Numpy` seperti untuk vektor.

**Penjumlahan dan perkalian skalar matriks**

Penjumlahan dan perkalian skalar matriks bekerja dengan cara yang sama seperti untuk vektor. Namun, **perkalian matriks** antara dua matriks, $P$ dan $Q$, didefinisikan ketika $P$ adalah matriks ${m} \times {p}$ dan $Q$ adalah matriks ${p} \times {n}$. Hasil dari $M = PQ$ adalah matriks $M$ yang berukuran $m \times n$. Dimensi dengan ukuran $p$ disebut **dimensi matriks bagian dalam**, dan dimensi matriks bagian dalam harus cocok (yaitu, jumlah kolom di $P$ dan jumlah baris di $Q$ harus sama) agar perkalian matriks didefinisikan. Dimensi $m$ dan $n$ disebut **dimensi matriks bagian luar**. Secara formal, jika $P$ adalah ${m} \times {p}$ dan Q adalah ${p} \times {n}$, maka $M = PQ$ didefinisikan sebagai

$$
M_{ij} = \sum_{k=1}^p P_{ik}Q_{kj}
$$

Produk dari dua matriks $P$ dan $Q$ dalam Python dicapai dengan menggunakan metode `dot` di Numpy.

**Transpos matriks**

Transpos matriks adalah pembalikan barisnya dengan kolomnya. Transpos dilambangkan dengan superskrip, $T$, seperti $M^T$ adalah transpos dari matriks $M$. Di Python, metode **T** untuk array Numpy digunakan untuk mendapatkan transpos. Misalnya, jika $M$ adalah matriks, maka $M.T$ adalah transposnya.

**Contoh**

Diketahui matriks Python $P = [[1, 7], [2, 3], [5, 0]]$ dan $Q = [[2, 6, 3, 1], [1, 2, 3, 4]]$. Hitung produk matriks dari $P$ dan $Q$. Tunjukkan bahwa produk dari $Q$ dan $P$ akan menghasilkan Error.

In [1]:
P = np.array([[1, 7], [2, 3], [5, 0]])
Q = np.array([[2, 6, 3, 1], [1, 2, 3, 4]])
print("Matrix P = \n",P)
print("Matrix Q = \n",Q)
print()

t = np.dot(P, Q)
print(t)

try:
    s = np.dot(Q,P)
    print(t)
except ValueError as ve:
    print("-"*80)
    print("ValueError : ", ve)


NameError: name 'np' is not defined

### Determinan Matrix

**Matriks persegi** adalah matriks yang memiliki jumlah baris dan kolom yang sama. **Determinan** adalah sifat penting dari matriks persegi. Determinan dilambangkan dengan $det(M)$, baik dalam matematika maupun dalam paket `linalg` Numpy, terkadang juga dilambangkan sebagai $|M|$.

Berikut adalah beberapa contoh penggunaan determinan:

* **Menghitung volume objek:** Determinan dapat digunakan untuk menghitung volume objek geometris, seperti tetrahedron, kuboid, dan prisma.
* **Menghitung invers matriks:** Determinan digunakan untuk menghitung invers matriks. Invers matriks adalah matriks yang dikalikan dengan matriks aslinya akan menghasilkan matriks identitas.
* **Menentukan apakah suatu himpunan vektor linier independen:** Determinan dapat digunakan untuk menentukan apakah suatu himpunan vektor linier independen. Himpunan vektor linier independen jika dan hanya jika determinannya tidak sama dengan nol.

Untuk matriks $2 \times 2$, determinannya dihitung sebagai berikut:

$$
|M| = \begin{bmatrix}
a & b \\
c & d\\
\end{bmatrix} = ad - bc$$

Demikian pula, untuk matriks $3 \times 3$, determinannya dihitung sebagai berikut:

$$
\begin{eqnarray*}
|M| = \begin{bmatrix}
a & b & c \\
d & e & f \\
g & h & i \\
\end{bmatrix} & = & a\begin{bmatrix}
\Box &\Box  &\Box  \\
\Box & e & f \\
\Box & h & i \\
\end{bmatrix} - b\begin{bmatrix}
\Box &\Box  &\Box  \\
d & \Box & f \\
g & \Box & i \\
\end{bmatrix}+c\begin{bmatrix}
\Box &\Box  &\Box  \\
d & e & \Box \\
g & h & \Box \\
\end{bmatrix} \\
&&\\
& = & a\begin{bmatrix}
e & f \\
h & i \\
\end{bmatrix} - b\begin{bmatrix}
d & f \\
g & i \\
\end{bmatrix}+c\begin{bmatrix}
d & e \\
g & h \\
\end{bmatrix} \\ 
&&\\
& = & aei + bfg + cdh - ceg - bdi - afh
\end{eqnarray*}$$

Kita dapat menggunakan pendekatan yang sama untuk menghitung determinan untuk matriks dengan dimensi lebih tinggi, tetapi jauh lebih mudah untuk menghitung menggunakan Python. Kita akan melihat contoh di bawah ini tentang cara menghitung determinan di Python.

**Matriks identitas** adalah matriks persegi dengan angka satu pada diagonal dan angka nol di tempat lain. Matriks identitas biasanya dilambangkan dengan $I$, dan serupa dengan identitas bilangan real, 1. Artinya, mengalikan matriks apa pun dengan $I$ (dengan ukuran yang kompatibel) akan menghasilkan matriks yang sama.

Berikut adalah contoh menghitung determinan matriks dalam Python:

In [87]:
import numpy as np

# Membuat matriks 2x2
M = np.array([[1, 2], [3, 4]])

# Menghitung determinan matriks
determinant = np.linalg.det(M)

print(determinant)

-2.0000000000000004


**Contoh**

Carilah nilai Determinan dari Matrix $M = [[0, 2, 1, 3], [3, 2, 8, 1], [1, 0, 0, 3], [0, 3, 2, 1]]$. \\

Buktikan bahwa perkalian Matrix $M\cdot I$ menghasilkan Matrix $M$

In [88]:
from numpy.linalg import det

M = np.array([[0,2,1,3], 
             [3,2,8,1], 
             [1,0,0,3],
             [0,3,2,1]])
print('M:\n', M)

print('Determinant: %.1f'%det(M))
I = np.eye(4)
print('I:\n', I)
print('M*I:\n', np.dot(M, I))

M:
 [[0 2 1 3]
 [3 2 8 1]
 [1 0 0 3]
 [0 3 2 1]]
Determinant: -38.0
I:
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
M*I:
 [[0. 2. 1. 3.]
 [3. 2. 8. 1.]
 [1. 0. 0. 3.]
 [0. 3. 2. 1.]]


### Inverse Matrix

**Invers** dari suatu matriks persegi $M$ adalah matriks dengan ukuran yang sama, $N$, sehingga $M \cdot N = I$. Invers dari suatu matriks serupa dengan invers bilangan real. Misalnya, invers dari 3 adalah $\frac{1}{3}$ karena $(3)(\frac{1}{3}) = 1$. Suatu matriks dikatakan **inversibel** jika memiliki invers. Invers dari suatu matriks adalah unik; yaitu, untuk suatu matriks inversibel, hanya ada satu invers untuk matriks tersebut. Jika $M$ adalah matriks persegi, inversnya dilambangkan dengan $M^{-1}$ dalam matematika, dan dapat dihitung dalam Python menggunakan fungsi *inv* dari paket *linalg* Numpy.

Untuk matriks $2 \times 2$, solusi analitik dari invers matriks adalah:

$$
M^{-1} = \begin{bmatrix}
a & b \\
c & d\\
\end{bmatrix}^{-1} = \frac{1}{|M|}\begin{bmatrix}
d & -b \\
-c & a\\
\end{bmatrix}$$

Perhitungan invers matriks untuk solusi analitik menjadi rumit dengan meningkatnya dimensi matriks, ada banyak metode lain yang dapat membuat segalanya lebih mudah, seperti eliminasi Gauss, metode Newton, Dekomposisi Eigen, dan sebagainya. Kami akan memperkenalkan beberapa metode ini setelah kami mempelajari cara memecahkan sistem persamaan linier, karena prosesnya pada dasarnya sama.

Ingatlah bahwa 0 tidak memiliki invers untuk perkalian dalam pengaturan bilangan real. Demikian pula, ada matriks yang tidak memiliki invers. Matriks-matriks ini disebut **singular**. Matriks yang memiliki invers disebut **nonsingular**.

Salah satu cara untuk menentukan apakah suatu matriks singular adalah dengan menghitung determinannya. Jika determinannya 0, maka matriks tersebut singular; jika tidak, matriks tersebut nonsingular.

**TRY IT!** Matriks $M$ (pada contoh sebelumnya) memiliki determinan yang bukan nol. Hitung invers dari $M$. Tunjukkan bahwa matriks $P = [[0, 1, 0], [0, 0, 0], [1, 0, 1]]$ memiliki nilai determinan 0 dan oleh karena itu tidak memiliki invers.

In [89]:
import numpy as np

# Membuat matriks 2x2
M = np.array([[1, 2], [3, 4]])

# Menghitung invers matriks
inverse_of_M = np.linalg.inv(M)

print(inverse_of_M)

[[-2.   1. ]
 [ 1.5 -0.5]]


In [90]:
# Membuat matriks 3x3
P = np.array([[0, 1, 0], [0, 0, 0], [1, 0, 1]])

# Menghitung determinan matriks
determinant_of_P = np.linalg.det(P)

print(determinant_of_P)

0.0


Karena determinan dari matriks $P$ adalah 0, maka matriks $P$ adalah singular dan tidak memiliki invers.

### Condition Number, Rank, Augmented Matrix


**Matriks yang hampir singular** (yaitu, determinannya mendekati 0) disebut **berkondisi buruk**. Meskipun matriks berkondisi buruk memiliki invers, mereka bermasalah secara numerik dengan cara yang sama seperti membagi angka dengan angka yang sangat, sangat kecil bermasalah. Artinya, dapat menghasilkan perhitungan yang menghasilkan overflow, underflow, atau angka yang cukup kecil untuk menghasilkan kesalahan pembulatan yang signifikan (Jika Anda lupa konsep-konsep ini, segarkan diri Anda dengan materi di bab 9). **Angka kondisi** adalah ukuran seberapa buruk kondisi suatu matriks, dan dapat dihitung menggunakan fungsi *cond* Numpy dari *linalg*. Semakin tinggi angka kondisi, semakin dekat matriks dengan singular.

**Pangkat** dari matriks ${m} \times {n}$ $A$ adalah jumlah kolom atau baris linier independen dari $A$, dan dilambangkan dengan rank($A$). Dapat ditunjukkan bahwa jumlah baris linier independen selalu sama dengan jumlah kolom linier independen untuk matriks apa pun. Matriks disebut **pangkat penuh** jika rank $(A)=\min(m,n)$. Matriks, $A$, juga pangkat penuh jika semua kolomnya linier independen. **Matriks teraugmentasi** adalah matriks, $A$, yang digabungkan dengan vektor, $y$, dan ditulis $[A,y]$. Ini biasanya dibaca "$A$ teraugmentasi dengan $y$." Anda dapat menggunakan *np.concatenate* untuk menggabungkan keduanya. Jika $rank([A,y]) = {rank}(A) + 1$, maka vektor, $y$, adalah informasi "baru". Artinya, tidak dapat dibuat sebagai kombinasi linier dari kolom-kolom di $A$. Pangkat adalah sifat penting dari matriks karena hubungannya dengan solusi persamaan linier, yang dibahas di bagian terakhir bab ini.

Berikut adalah beberapa contoh penggunaan pangkat matriks:

* **Menentukan apakah suatu sistem persamaan linier memiliki solusi:** Suatu sistem persamaan linier memiliki solusi jika dan hanya jika pangkat matriks koefisiennya sama dengan pangkat matriks teraugmentasinya.
* **Menentukan apakah suatu himpunan vektor linier independen:** Suatu himpunan vektor linier independen jika dan hanya jika pangkat matriks yang dibentuk oleh vektor-vektor tersebut sama dengan jumlah vektor-vektor tersebut.
* **Menghitung dimensi ruang nol suatu matriks:** Dimensi ruang nol suatu matriks adalah selisih antara jumlah kolom matriks dan pangkat matriks tersebut.

**Contoh**

Carilah conditon number dan rank dari Matrix $A = [[1, 1, 0], [0, 1, 0], [1, 0, 1]]$.

Jika $y = [[1], [2], [1]]$, Carilah augmented matrix [A, y]. 

In [8]:
from numpy.linalg import \
             cond, matrix_rank

A = np.array([[1,1,0],
              [0,1,0],
              [1,0,1]])

print('Condition number:\n', cond(A))
print('Rank:\n', matrix_rank(A))
y = np.array([[1], [2], [1]])
A_y = np.concatenate((A, y), axis = 1)
print('Augmented matrix:\n', A_y)

NameError: name 'np' is not defined

---

## Tugas
- Selesaikan soal-soal berikut dengan membuat program masing-masing soal sesuai yang ditanyakan.
- Kerjakan dengan membuat cell code baru di bawah setiap soal
- Upload file .ipynb yang telah berisi jawaban lengkap pada Akun Github dengan membuat Repository baru


1. Tentukan determinan matriks berikut:

$$\displaystyle A = \left( \begin{array}{cc}
1 & 2 \\
3 & 4
\end{array} 
\right)
$$

In [7]:
import numpy as np 
from numpy.linalg import det
A = np.array([[1, 2,], [3, 4]])
print('Determinant: %.1f'%det(A))

Determinant: -2.0


2. Tentukan invers Matriks Berikut:

$$\displaystyle B = \left( \begin{array}{cc}
10 & -22 \\
3 & 45
\end{array} 
\right)
$$

In [8]:
import numpy as np

# Membuat matriks 2x2
B = np.array([[10, -22], [3, 45]])

# Menghitung invers matriks
inverse_of_B = np.linalg.inv(B)

print(inverse_of_B)

[[ 0.0872093   0.04263566]
 [-0.00581395  0.01937984]]


3. Tentukan apakah matriks berikut berkondisi buruk:
$$\displaystyle C = \left( \begin{array}{cc}
1 & 10^{-10} \\
10^{-10} & 1
\end{array} 
\right)
$$

In [9]:
import numpy as np
from numpy.linalg import \
             cond, matrix_rank

C = np.array([[1,10^-10],
              [10^-10,1],])

print('Condition number:\n', cond(C))
print('Rank:\n', matrix_rank(C))

Condition number:
 1.6666666666666667
Rank:
 2


4. Tentukan apakah sistem persamaan linier berikut memiliki solusi. Jika ada, bagaimana solusinya?

$$\displaystyle A = \left( \begin{array}{cc}
1 & 2 \\
3 & 4
\end{array} 
\right) $$


$$\displaystyle
b =  \left( \begin{array}{cc}
5 & 6 
\end{array} 
\right) \\
$$

In [21]:
import numpy as np
            

A = np.array([[1,2], [3,4]])

b = np.array([[5], [6]])
A_b = np.concatenate((A, b), axis = 1)
print('Augmented matrix:\n', A_b)

Augmented matrix:
 [[1 2 5]
 [3 4 6]]


5. Tentukan dimensi ruang nol matriks berikut:


$$\displaystyle
C =
\left(
\begin{array}{ccc}
1 & 2 & 3 \\
4 & 5 & 6 \\
7 & 8 & 9
\end{array}
\right)
$$